internetarchive/brozzler

brozzler/__init__.py, brozzler/frontier.py
Dynamically set number of shards and replicas based on number of servers in rethinkdb cluster
=> uncommented init imports, removed required job_id in Frontier.finished

bin/brozzler-new-site
Just making it so the script can actually run.
I think brozzler-new-site is still partly broken though, the worker crashes complaining that job_id is None. I guess one needs to be passed to Site(). Wasn't sure if it should take a job id as an argument or generate one randomly.
I have since realised that brozzler-new-job is probably what I should be looking at instead but had already patched this so figured I'd submit it anyway just in case. ;-)
=> brozzler-new-site: Fix warcprox_meta's default value and json import

brozzler/browser.py
--disable-extensions keeps Chromium from installing Chrome extensions—lastpass was very troublesome until I added this.
There's a great list of Chromium command line switches here: http://peter.sh/experiments/chromium-command-line-switches/
I'm curious to know why brozzler uses --window-size=1100,900
I'm curious to know wh
=> disable browser extensions

brozzler/cli.py, brozzler/job.py, brozzler/job_schema.yml, setup.py
This adds a [Cerberus](http://docs.python-cerberus.org/en/stable/) schema for validating job files. This ensures that typos can't be silently introduced in field names and that type errors are detected upfront before jobs are submitted to rethinkdb.
The error messages produced are fairly descriptive:
```
brozzler-new-job: invalid job file: job.yml
helloworld: [unknown field]
seeds:
- 0:
- url: [must be of url type]
4:
- url: [required field]
time_limit: [min value is 0]
```
=> Validate job conf against a simple schema

brozzler/browser.py
Accept-Encoding: Identity,  avoiding content-encoding: br, which we've been getting from facebook, but is not currently supported by wayback.
=> ARI-5008 / ARI-5065 ExtraHTTPHeaders Accept-Encoding fix Identity

README.rst
more specifically, on OS X El Capital, 10.11.06, with macports installs of many packages...
=> rethinkdb installer works for me

README.rst
libpepflashplayer.so is no longer included in the Chrome release package.  Adobe are [resuming Linux releases](http://blogs.adobe.com/flashplayer/2016/08/beta-news-flash-player-npapi-for-linux.html) and the PPAPI plugin is available from their [download site](https://get.adobe.com/flashplayer/otherversions/).
=> Update Flash plugin instructions

brozzler/behaviors.d/mouseovers.js.template, brozzler/behaviors.yaml
PR as requested. Although this literally is just a copy paste and string replace of 'click' with 'mouseover'.
Let me know if you'd like me to rework this in some other fashion. I did at first consider adding mouseover to simpleclicks.js rather than duplicating it but I realised I was just going to get bogged down trying figure out the most optimal approach.
It seems like a generic behavior that accepts a list of events + selectors might be a useful thing to have. Something like this:
``` yaml
events:
- mouseover: .menu-item a
- click: .tab
- focus: input
- click: button.dostuff
- keypress:
selector: .scrollything
key: ArrowDown
```
But I haven't worked through enough examples yet to be confident of what's useful and what's premature generalisation.
=> Add a mouseovers behavior

README.rst
Also make it clearer that this hasn't been tested much.
=> update headless chrome instructions for regular chrome builds

brozzler/browser.py, brozzler/cli.py, brozzler/worker.py
Current brozzler code in `brozzler.browser.Browser.browse_page` always runs the `visit_hashtags` and `extract_outlinks` methods. In some cases when you just need to brozzle multiple single pages and you don't need to crawl entire sites, this is not useful and it adds overhead.
With this MR, we add the `--skip-visit-hashtags` and `--skip-extract-outlinks` methods to `brozzle-page` and `brozzler-worker` commands.
=> new skip cli options for brozzle-page and brozzler-worker

brozzler/js-templates/facebook.js
ARI-5407
facebook now requires us, sometimes, at least, to click a See More link to access most post content
tested and deployed per ARI-5407
=> Add click selector for facebook’s new See More link

brozzler/browser.py
``ignore_cert_errors`` is passed to ``Chrome`` via ``Browser`` via ``BrowserPool` here:
https://github.com/internetarchive/brozzler/blob/master/brozzler/worker.py#L120
it is not doing anything in ``Browser.browser_page``.
=> Remove redundant method parameter.

brozzler/worker.py
Enabled by default (of course).
Speed is significantly improved when it is disabled.
=> Make youtube-dl optional in BrozzlerWorker.brozzle_page

brozzler/worker.py
I'm sorry but with my previous commit I introduced a bug in
``BrozzlerWorker._needs_browsing`` method.
More specifically, if the ``brozzler_spy`` param is False (this happens
when ``youtube_dl`` is disabled), ``_needs_browsing`` method returns
always ``False`` and this messes with ``brozzle_page`` workflow. The
browser is never visiting the page.
I'm fixing this here.
=> bugfix for BrozzlerWorker._needs_browsing

brozzler/worker.py
``Browser.browser_page`` has the ``on_request`` parameter but it is on
used by ``BrozzlerWorker._browse_page`` where we invoke it.
I add this to ``BrozzlerWorker.brozzle_page`` and pass it also to
``BrozzlerWorker._browser_page``. Now, it is possible to use this
callback from other applications when calling
``BrozzlerWorker.brozzle_page``.
=> Pass missing on_request callback to BrozzlerWorker methods

brozzler/browser.py, brozzler/worker.py
The page loading timeout was hard-coded to 300s. With this change,
we make it configurable with a default value of 300.
=> Configurable page timeout

brozzler/browser.py, brozzler/worker.py
``behavior_timeout`` is hardcoded to 900s. With this MR we make it
configurable with a default value of 900. We add a new variable to
``BrozzlerWorker`` and ``Browser``.
=> Make behavior_timeout configurable

brozzler/frontier.py, tests/test_frontier.py
fix resume_job function, the job was not able to resume because the job stop_requested value was not reset.
After stopping a brozzler job with the brozzler-stop-crawl, calling the function resume_job was not able to resume the crawl. Altought resume job cannot work because of other job stop conditions, with a normal workflow like: brozzler-stop-crawl ---> resume_job will work now.
=> fix resume_job

brozzler/chrome.py
Chromium browser docs describe this as follows:
_Disable several subsystems which run network requests in the
background. This is for use when doing network performance testing to
avoid noise in the measurements._
Testing indicates that irrelevant HTTP requests like the following stop
with this improvement.
```
HEAD http://ugfgntuqva/ HTTP/1.1
```
=> Add --disable-background-networking chromium flag

brozzler/__init__.py, brozzler/browser.py
Brozzler has hard-coded the JS templates logic in  ``brozzler/behaviors.yaml``
and ``brozzler/js-templates/`` locations. With this change, you can use
the optional ``behaviors_dir`` ``browser.browse_page`` parameter to set a
custom location and use any potential JS behaviors.
=> Configurable JS templates location

brozzler/chrome.py
The ``self._home_tmpdir.cleanup()`` cmd is not always executed when
stopping Chrome. As a result, a large number of ``/tmp/tmpXXX`` dirs are
created in production.
The reason is that ``Chrome.stop()`` execution can stop in the ``return``
statement in the following line:
https://github.com/internetarchive/brozzler/blob/master/brozzler/chrome.py#L268
and ``cleanup()`` does not run.
Moving the ``cleanup()`` in the ``finally`` part of the
``try/catch/finally`` block makes it run always in the end of
``Chrome.stop()`` and cleans up the tmp directory in any case.
=> Fix to delete tmpdir on Chrome.stop()

brozzler/browser.py
logging for AITFIVE-1529—do we receive Page.interstitialShown message for anything apart from http auth?
=> log Page.interstitialShown

brozzler/worker.py
This should reduce contention over the "sites" table, which should help
keep more available browsers busy across the cluster.
=> lengthen site session brozzling time to 15 minutes

brozzler/browser.py, brozzler/frontier.py, brozzler/worker.py, tests/test_frontier.py
Archive-it brozzler cluster is not keeping all available browsers busy even if there are more active sites than available browsers. It appears this is because claiming a site to brozzle takes too long sometimes, due to contention over the table.
Claim sites to brozzle in batches to reduce contention over sites table. Workers claim up to `(available_browsers + 1) // 2` at a time.
=> WIP: claim sites to brozzle in batches to reduce contention over sites table

README.rst, brozzler/browser.py, brozzler/chrome.py, brozzler/cli.py, brozzler/easy.py
Rebased https://github.com/internetarchive/brozzler/pull/84
and added a browser version check.
In the past the browser version dependency has always been fuzzy. Now it will be clear. See description on https://github.com/internetarchive/brozzler/pull/84
=> Block google analytics URLs using new Network.setBlockedURLs API 

brozzler/chrome.py
``--disable-background-timer-throttling`` and ``--disable-renderer-backgrounding``:
karma JS test runner uses these to improve chrome performance
https://github.com/karma-runner/karma-chrome-launcher/issues/123
``--disable-hang-monitor``: Suppresses hang monitor dialogs in renderer
processes. This may allow slow unload handlers on a page to prevent the
tab from closing, but the Task Manager can be used to terminate the
offending process in this case.
``--mute-audio``: obvious.
The following are part of google safe browsing features:
``--disable-client-side-phishing-detection``
``--safebrowsing-disable-auto-update``
``--safebrowsing-disable-download-protection``
Good reference with all chromium cli opts: https://peter.sh/experiments/chromium-command-line-switches/
=> Add chromium CLI flags to improve capture performance

brozzler/browser.py
Use JSON separators without spaces to reduce json size.
Its already used elsewhere in Brozzler but not here.
=> Send more compact JSON to browser

brozzler/__init__.py
Every time we run a JS behavior, we load a Jinja2 template. By default, Jinja2 has option `auto_reload=True`. This mean that every time a template is requested the loader checks if the source file changed and if yes, it will reload the template. For higher performance it’s possible to disable that.
Also note that Jinja caches 400 templates by default.
Ref: http://jinja.pocoo.org/docs/2.10/api/
In Brozzler, we don't make changes to JS templates while the system is running. So, there is no point in having `auto_reload=True`.
=> Disable Jinja2 template auto_reload for higher performance

brozzler/chrome.py
By default chromium creates multiple renderer processes (each running
multiple threads) for each instance of a site the user visits. What we
see from `ps auxcf` output is the following:
```
\_ chromium-browse
\_ chromium-browse
|   \_ chromium-browse
|       \_ chromium-browse
|       \_ chromium-browse
|       \_ chromium-browse
```
Using the `--single-process` option, we run all renderers in the same
process, saving the overhead of running multiple processes. `ps auxcf`
output is the following:
```
\_ chromium-browse
\_ chromium-browse
\_ chromium-browse
```
Performance is improved a bit and I guess that using this in large scale
Brozzler deployments will have even better performance effects.
The potential problem of `--single-process` is stability (if a renderer
crashes, the whole …
=> Use single process model for chromium-browser

brozzler/frontier.py, brozzler/model.py
Other approach was too slow and caused db contention.
New approach avoids (slow) rethinkdb join by max_claimed_sites job
parameter to each of the job's sites. Uses rethinkdb fold() to count
claimed sites and enforce max_claimed_sites within a single query.
=> reimplement max_claimed_sites

brozzler/behaviors.yaml
ARI-5747
update selector for detail image
=> update instagram behavior

brozzler/robots.py, tests/test_cluster.py, tests/test_units.py
Policy is similar to heritrix's (changed fairly recently).
https://github.com/internetarchive/heritrix3/pull/187/files
Includes tests.
=> treat any error fetching robots.txt as "allow all"

brozzler/cli.py, setup.py
Useful for clearing cruft from rethinkdb, especially the `pages` table, which can get huge.
=> brozzler-purge - purge crawl state from rethinkdb

brozzler/frontier.py, brozzler/worker.py, tests/test_frontier.py
enforce time limit based on all the time that a site was in active
rotation, including time it spent waiting for its turn to be brozzled;
this undoes the change from b9640b8a30c934, because now it seems that
was the wrong decision (brozzler jobs with many seeds and low
max_claimed_sites hanging around forever)
=> change time limit enforcement

brozzler/behaviors.yaml, brozzler/js-templates/umbraBehavior.js.j2
the new try/catch block wrapping iframe additions to the documents var fixes the issue the skipIframes param addressed. Let's keep things simple and remove skipIframes.
=> no skipIframes for umbraBehavior

brozzler/chrome.py
Add `Chrome` options `disk_cache_dir` and `disk_cache_size` which add chromium
options `--disk-cache-dir=<DIR>` and `--disk-cache-size=N` (bytes).
=> Add disk cache options to Chrome

brozzler/model.py
which encumbers the validation with additional requirements,
specifically makes it difficult to validate a subclass of `dict` because
it expects a constructor that works like dict.__init__()
=> don't attempt cerberus normalization

tests/test_brozzling.py
We used `self.headers.getheader` which no longer works. We replace it
with `self.headers.get`.
We change the code to write binary data to `self.wfile` because we get
an exception for writing str and/or None.
=> Fix test_brozzling::httpd fixture

brozzler/browser.py
AMP analytics is part of Google analytics. We need to block it for
similar reasons. Current URL is
```
https://cdn.ampproject.org/v0/amp-analytics-0.1.js
```
but we have also seen:
```
https://cdn.ampproject.org/rtv/011906111828200/v0/amp-analytics-0.1.js
```
That's why we suggest the following pattern to block both:
```
*cdn.ampproject.org/*/amp-analytics*.js
```
AMP analytics reference:
https://developers.google.com/analytics/devguides/collection/amp-analytics/
=> Block AMP analytics JS script

brozzler/chrome.py
When the chrome process dies and we try to read STDIN/STDERR, we get
`ValueError: I/O operation on closed file` or
`OSError: [Errno 9] Bad file descriptor`.
We modify `readline_nonblock` method to return the buffer it read up to
this point.
=> Improve exception handling when reading STDIN/STDERR

brozzler/browser.py
If you use a JS behavior timeout smaller than 7 sec, the JS behavior
will always need 7 sec because `sleep(7)` is hard-coded there.
We make a minor addition to use `min(timeout, 7)` for sleep so it will
finish faster when using a smaller JS behavior timeout.
=> More accurate JS behavior timeout

brozzler/behaviors.yaml, brozzler/js-templates/umbraBehavior.js.j2
Initial PR: https://github.com/internetarchive/brozzler/pull/163
This pull request add support for the Facebook ads Library available at: https://www.facebook.com/ads/library/
The behavior added is to open and close the detailed metrics of each ads.
In addition to that, I've also added a fix to the closing mechanism, and based on @nlevitt comments, the closing now doesn't use doTarget anymore.
Thanks!
=> Add support for Facebook ads library and fix closing

brozzler/browser.py
When capturing a page, we receive a lot of messages from chrome.
Examining these message, we see that we can reduce them a bit to speed
up Brozzler.
We always use `Console.enable` which returns all browser console output.
Also, we always use `Runtime.enable`. Doc says:
https://chromedevtools.github.io/devtools-protocol/1-3/Runtime#method-enable
Enables reporting of execution contexts creation by means of
executionContextCreated event. When the reporting gets enabled the event
will be sent immediately for each existing execution context.
These outputs are useful when debugging but not in production.
If we disable them, we reduce the websocket traffic and improve
performance. With this PR, we enable them only when the current logging
level is `DEBUG`.
Counting the number of messages before …
=> Enable Console and Runtime outputs only when debugging

brozzler/dashboard/__init__.py
Is this helpful?? I want to be able to expose brozzler-dashboard to other interfaces and ports. Any reason for not having this?
=> Add option to specify port and interface binding on brozzler-dashboard

brozzler/browser.py, brozzler/worker.py
Add option `full_page` to `Browser.screenshot`. The default behavior
remains the same.
We get inspiration from puppeteer to capture a screenshot of the full
page:
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L898
Add option `screenshot_full_page=False` to `Browser.browse_page` to use
the new feature when capturing a page.
=> Add option to capture full page screenshot

brozzler/browser.py
After analysing capture logs, we see that we didn't block many
google-analytics related URLS which are used for web statistics. We add
these to the blocked URLs.
In addition, we improve existing block rules. We used to block
`*google-analytics.com/analytics.js` but many sites used some kind of
param in the end so these URLs weren't blocked. We add `*` in the end of
the existing rules to block these cases as well.
=> Block more google-analytics URLs

brozzler/behaviors.yaml, brozzler/js-templates/umbraBehavior.js.j2
This PR ads the capture of FB Library ads variants.
It needs the `childSelector` action proposed in this pull request: https://github.com/internetarchive/brozzler/pull/176
=> Add capture of Facebook ads variants

brozzler/js-templates/umbraBehavior.js.j2
This pull request add a new action for the behavior system. 
This action is named `childSelector` (I'm open to any better name!) and is executed after `selector` and before `closeSelector`.
=> Add childSelector action

brozzler/behaviors.yaml
Fix the CSS class needed to click variants ads on the Facebook ads Library due to recent Facebook changes.
Example link for this selector: https://www.facebook.com/ads/library/?active_status=all&ad_type=political_and_issue_ads&country=ALL&impression_search_field=has_impressions_lifetime&q=Rhubarb
=> Fix Facebook Ads Library variants selector

brozzler/chrome.py
When trying to run Brozzler in docker, we get the following error:
```
Failed to move to new namespace: PID namespaces supported, Network
namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap
```
This happens because chromium uses sandboxing for increased security by
default and its not supported when running in a container.
Adding chromium option `--no-sandbox` fixes the problem.
This issue is common, I found various reports about it like this:
https://github.com/Zenika/alpine-chrome/issues/33
=> Enable running in docker / k8s

brozzler/__init__.py, brozzler/worker.py, tests/test_units.py
https://github.com/internetarchive/brozzler/pull/183#issuecomment-560562807
"We've had a number of cases where a page kept failing for one reason or
another, and it's bad. We can end up with tons of duplicate captures,
the crawl is not able to make progress, and the overall performance of
the cluster is impacted in cases like yours, where a browser is sitting
there doing nothing for five minutes."
=> consider page completed after 3 failures

brozzler/browser.py, brozzler/cli.py, brozzler/worker.py
Currently, when we run `Browser.browse_page`, we run JS behaviors after
we navigate to a page regardless of its status.
Maybe the page wasn't found (4xx) or unreachable for any reason (5xx).
In that case, we could skip running behaviors to save time and
resources.
With this PR, we add a new var to store navigated page HTTP status in
`WebsockReceiverThread.page_status`. We use this in
`Browser.browser_page` to skip behaviors, outlink and hashtag extraction
when page status is 4xx/5xx.
Note that we don't skip screenshots as it could be useful to have a
picture of an error page in some cases.
Finally, we add option `simpler404` to enable this (it is disabled by default).
=> Skip running behaviors when page is 4xx or 5xx

brozzler/js-templates/try-login.js.j2, tests/htdocs/site11/form2.html, tests/test_brozzling.py
Some sites don't allow you to login without clicking on a button to open a retracted modal.
This update to the login code allows Brozzler to click on all elements that we think are related to opening a login modal. Then, if there isn't a regular form, we will attempt to fill out abnormal form schemes. The test_try_login test has been expanded for the new type of login form we are supporting.
=> Expanding Brozzler's logging in capabilities

ansible/roles/brozzler-worker/tasks/main.yml, ansible/roles/rethinkdb/tasks/main.yml
RethinkDB wasn't installing, due to [a change in download servers.](https://rethinkdb.com/blog/download-server-changes) The latest version of Numpy no longer supports Python 3.5, so to maintain backwards compatibility, when Python 3.5 is being used we install a older version.
I'm still looking into the main test failure I've currently seen, test_no_proxy not passing due to Travis timing it out. Thanks!
=> Attempt to fix the tests

README.rst
It has been removed in 934190084c73699747cf3f4c4d2ee7e268927eae.
=> readme: remove proxy from job configuration

brozzler/browser.py
The user may set `behavior_timeout=0`. This means that they don't want
to run the behavior. As it is now, Brozzler will invoke
`brozzler.behavior_script` to load the script and `self.run_behavior`
to execute it.
We will run the behavior using `Runtime.evaluate` but then it will be
terminated immediately because of timeout=0.
It is better to skip behavior loading and running when
`behavior_timeout=0`.
=> Skip loading behavior when behavior_timeout=0

brozzler/browser.py, brozzler/worker.py
`Browser.extract_outlinks` has a default `timeout=60` parm that cannot be
changed in any way. (It is always invoked using `extract_outlinks()`.
We add param `extract_outlinks_timeout=60` to `BrozzlerWorker` and
`Browser.browse_page` to allow that.
=> Add option extract_outlinks_timeout

brozzler/ydl.py
Fixes issue where videos pulled in on User pages prevent html seeds from being crawled when a data limit is met
=> Added user page extractor type to ytdl monkeypatch

brozzler/browser.py
When one of the outlinks is `http://-1/` `urlcanon.whatwg` raises an
unhandled exception `ipaddress.AddressValueError` and the capture fails.
We can skip the problematic outlink and keep the rest without crashing.
=> Skip invalid outlink

brozzler/browser.py, brozzler/cli.py, brozzler/js-templates/stealth.js, brozzler/worker.py
The aim is to prevent Brozzler detection and blocking by antibot
systems. To do that, we need to run some JS before any other code runs
on page load and mock specific browser attributes which indicate that
Brozzler is a bot.
We add the option `stealth` in `Browser`, `brozzler.cli` and
`BrozzlerWorker`. It is disabled by default.
If enabled, we run `stealth.js` which is executed before anything else
on the page via `Page.addScriptToEvaluateOnNewDocument`.
For now, we mock only the graphics driver attributes.
If this is OK, we can add more antibot evasions in the same script.
There are many antibot tests, we are using this: https://bot.sannysoft.com/
Inspired mainly by:
https://www.npmjs.com/package/puppeteer-extra-plugin-stealth
=> Add stealth parameter to avoid antibot systems

brozzler/js-templates/stealth.js
Set `navigator.platform = 'Win32'` instead of the default `Linux` as we
usualy run Brozzler on Linux.
Randomize the `navigator.deviceMemory` and
`navigator.hardwareConcurrency` to avoid browser fingerprinting.
Define `window.Notification` which is not defined because we run Chrome
with CLI parameter `--disable-notifications`.
=> Add more stealth evasions

brozzler/browser.py
The screenshot is an additional thing we do when the capture is successful. Why get a screenshot of 4xx/5xx responses? Its just extra system load.
We already got the capture for archiving reasons.
=> Do not try to get a screenshot if status is 4xx, 5xx

brozzler/ydl.py
youtube video captures are now failing with yt-dlp v.2023.03.04. 
This update enables brozzler to use yt-dlp v.2023.07.06, and re-enables youtube video capture.
=> yt-dlp capture replayable mp4s again

setup.py
The latest `warcprox` 2.5.1 requirement
https://github.com/internetarchive/doublethink/blob/Py311/setup.py requires `rethinkdb>=2.4.9,<2.5` but Brozzler has `rethinkdb>=2.3,<2.4` and this creates a conflict if they are in the same virtualenv.
We update Brozzler to use the same dependency.
=> Update rethinkdb dependency

brozzler/ydl.py
yt-dlp updates in v.2023.10.13 benefit from modest changes in how brozzler imports yt-dlp, directly now, as well as skipping overriding urlopen and verbose logging.
=> improve yt-dlp import

brozzler/worker.py, brozzler/ydl.py
brozzler should capture pages before video
=> run yt-dlp after brozzling a page (if at all)

brozzler/worker.py, brozzler/ydl.py, setup.py
use local variables, instead of adding attributes to the page object, to avoid additional rethinkdb traffic
=> refine April ytdlp_last update

brozzler/browser.py
A performance improvement suggested here:
https://websocket-client.readthedocs.io/en/latest/faq.html#why-is-this-library-slow
=> add skip_utf8_validation parameter for websocket-client

brozzler/chrome.py
Chrome 130 automatically converts http to https even if the target URL is http. We disable this behavior because some target sites simply don't have https.
=> Disable automatic http to https transformation

brozzler/__init__.py, brozzler/browser.py, brozzler/chrome.py, brozzler/cli.py, brozzler/dashboard/__init__.py, brozzler/easy.py, brozzler/frontier.py, brozzler/model.py, brozzler/pywb.py, brozzler/robots.py, brozzler/worker.py, brozzler/ydl.py, setup.py, tests/test_cluster.py, tests/test_units.py
This ports the logging from `logging` to `structlog`. I've updated all of the logger instantiations along with all of the places `logging` was called. I've broken out most data that was being inlined into log statements so that it's now structured arguments to the log statements instead. I've also updated at least a few places to add some default parameters that will be included in all logging statements, but I think it'd be good to look at what other common variables we could use to link multiple log statements together. Specifically, at the moment:
* The yt-dlp class always logs the URL
* BrozzlerWorker always logs the thread
To start, I've kept structlog's default formatting. I know we're interested in keeping text-based logs as the default for now; we can talk whatever specifics we'd …
=> Set up structlog logging

setup.py
This group isn't actually installable right now because of the jinja dependency conflict.
I've been experimenting with using `uv` for development, and the unsatisfiable `easy` dependencies meant that `uv sync` couldn't work - it needs to be able to resolve the full dependency tree for every group of extras, even if they won't all be installed.
=> deps: remove `easy` group

.github/workflows/daily.yaml, .github/workflows/setup/action.yml, .github/workflows/tests.yml, brozzler/__init__.py, brozzler/worker.py, setup.py, tests/test_cli.py, tests/test_units.py
This adds two CI runs: a quick one that happens for every pull request and merge to master, and a longer one that happens daily. The long one, in my tests so far, took about six hours(!) - so it's not feasible for us to do on every pull request.
The pull request/master merge tests are all reliably passing right now, but the full suite isn't. I'm not clear if these are legitimate failures, or if it's a sign that some of the code it's testing has changed since it was written. Here's the full test run I ran on it overnight: https://github.com/mistydemeo/brozzler/actions/runs/13534089995/job/37822403796
I added a new installation group to setup.py because the `easy` group isn't currently installable, and some of the dependencies specified there need to be present for the tests to run.
=> test: add CI

pyproject.toml
This is just a minor tweak. I realized we manually install dev dependencies in a few places, but we didn't explicitly write them down anywhere.
=> deps: add dev deps to pyproject.toml

.github/workflows/daily.yaml
This was left at the default of six hours, but it timed out last night. I'll set it at eight hours to see if this is more reliable.
=> CI: extend daily job timeout

brozzler/__init__.py, brozzler/cli.py, brozzler/worker.py, brozzler/ydl.py
Although doublethink is an optional dependency to allow brozzler to be used as a library without it, in practice we had some mandatory import statements that prevented brozzler from being imported without it. This fixes that by gating off some of the imports and exports.
If doublethink is available, brozzler works as it is now. But if it isn't, we make a few changes:
* `brozzler.worker`, `brozzler.cli` and `brozzler.model` reexports are disabled
* One `brozzler.cli` function, which is used outside brozzler's own cli, has been moved into brozzler's `__init__.py`. For compatibility, it's reexported from `brozzler.cli`.
=> __init__.py: rework imports

brozzler/__init__.py, brozzler/browser.py, brozzler/chrome.py, brozzler/cli.py, brozzler/dashboard/__init__.py, brozzler/easy.py, brozzler/frontier.py, brozzler/model.py, brozzler/pywb.py, brozzler/robots.py, brozzler/worker.py, brozzler/ydl.py, tests/test_brozzling.py, tests/test_cli.py, tests/test_cluster.py, tests/test_frontier.py, tests/test_units.py, vagrant/vagrant-brozzler-new-site.py
Linting fixes based on running this exact invocation: `ruff check --target-version py37 .`. Also ran `ruff format --target-version py37 .` and `ruff check --target-version py37 --select I . --fix` to ensure proper formatting and import sorting was intact.
The fixes were manual, but largely mechanical and tried to be as unobtrusive as possible. There are many more opportunities for improvement that can come in subsequent passes.
=> ruff linting fixes

setup.py, uv.lock
distutils was removed beginning in Python 3.12, but it's used at runtime by rethinkdb 2.4.9. setuptools provides a copy of distutils, so we should make sure to install it when we're on Python 3.12 or newer until we're able to upgrade to a version of rethinkdb that no longer needs it.
See: https://www.python.org/downloads/release/python-3120/
=> deps: install setuptools on python 3.12+

brozzler/cli.py, brozzler/worker.py
I'd noticed that the `worker_id` param was missing from `BrozzlerWorker` calls that occurred within a `threading` context. Binding to the local logger instance seems to be more reliable than using global contextvars in this specific case.
Before:
```
2025-03-10 21:03:53 [warning  ] brozzler 1.6.9 - brozzler-worker starting [brozzler.worker.BrozzlerWorker.run(worker.py:732)]
```
After:
```
2025-03-10 21:04:19 [warning  ] brozzler 1.6.9 - brozzler-worker starting [brozzler.worker.BrozzlerWorker.run(worker.py:736)] worker_id=1
```
=> fix: bind worker_id inside BrozzlerWorker

tests/test_brozzling.py, tests/test_cluster.py, tests/test_frontier.py
Noticed that the full test run was failing because these tests had an import of just `brozzler`, but they need to call `brozzler.cli`: https://github.com/internetarchive/brozzler/actions/runs/13781502290/job/38540436699
=> test: fix test brozzler imports

.github/workflows/release.yml
This adds a tag-to-release Actions config based around `uv`.
This is triggered by pushing a tag with a new version; it will automatically kick off this job, which will publish the new version to PyPI on completion. We can push that tag from a PR or directly to master.
At the moment, this doesn't do anything to automatically create a GitHub release from the tag; we can do that manually for now. We don't currently have in-repo release notes for us to build an automated release from so this would be a largely manual process anyway.
We don't need to provide a token to `uv` to publish; instead, we just need to configure the repo for PyPI access using this: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
cc @vbanos
=> CI: add a simple tag-to-release config

brozzler/cli.py
I missed this item from the old log formatting config in the previous structlog PRs.
Sample (you can see it at the end of the dict):
```
2025-05-02 22:23:55 [info     ] disclaiming                    [brozzler.frontier.RethinkDbFrontier.disclaim_site(frontier.py:326)] site={'active_brozzling_time': 0.025920867919921875, 'behavior_parameters': None, 'claimed': True, 'id': '5b3b5293-596a-4124-b803-ebff954e32de', 'ignore_robots': False, 'last_claimed': datetime.datetime(2025, 5, 2, 22, 23, 55, 114000, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x105117140>), 'last_claimed_by': 'Angela.local:54589', 'last_disclaimed': datetime.datetime(2025, 5, 2, 22, 23, 34, 462000, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x1051739b0>), 'password': None, 'proxy': None, 'scope': {'accepts': [{'ssurt': …
```
=> cli: add thread name to event dict

.github/workflows/dependabot.yml
These were necessary in qa for the automated yt-dlp action to run to completion.
* `contents: write` is necessary to merge a pull request - `pull-requests: write` is for the PR itself, and doesn't grant merge permissions.
* Looks like the merge strategy has to be specified to `gh pr merge` if running in automated mode.
=> ci: two fixes to dependabot action

pyproject.toml, setup.py
I realized these were missed when removing the dynamic config in a previous PR.
=> Move classifiers from setup.py

brozzler/worker.py
We assigned this inside an exception handler, and allow processing to continue on after catching the exception.
=> worker: fix possibly-unbound status code

brozzler/worker.py
In testing a page with an embedded YouTube video with video exclusion enabled, I found that brozzler ended up capturing about 30MB of [UMP packets](https://github.com/gsuberland/UMP_Format/blob/main/UMP_Format.md). We should be filtering those out too.
=> Video exclusion: skip YouTube UMP packets too

.github/workflows/setup/action.yml, .github/workflows/tests.yml
My main motivation is that uv provides the Python 3.14 betas, so we can test with those. But this also simplifies the setup steps a bit.
=> ci: use uv

.github/workflows/tests.yml
3.14 beta 4 is very late in the cycle, so it seems like a good time for us to start testing with it to make sure we're ready.
=> ci: test with 3.14 beta

brozzler/__init__.py, brozzler/worker.py, tests/test_cli.py
This was flagged by ruff check - if we just want to find out if a package is available, and don't need to actually import it, we can use importlib.util.find_spec() to resolve it. This can lead to a moderate speedup too, since the import might be slow.
=> remove unnecessary imports, use find_spec

.github/workflows/setup/action.yml
This should speed up dependency installs.
=> ci: skip manpage generation

.github/workflows/tests.yml, tests/test_frontier.py
This was skipped before due to flakiness, but it seems to be both reliable and fast enough to be tolerable. It takes about 30 seconds to complete on my local machine.
I had to xfail the performance test, which wasn't passing for me in CI but works locally.
=> ci: run frontier tests

tests/test_units.py
This made the common mistake of putting `\.` instead of `\\.` in a non-raw string.
=> tests: fix invalid escape

brozzler/chrome.py, brozzler/cli.py, brozzler/worker.py
Previously, Chrome's headless mode was always turned on. This makes it optional when using Brozzler as a module. (If there's interest in a command-line option for this, I can add that too.)
=> Add `headless` option to Chrome.start

brozzler/browser.py, brozzler/worker.py
A couple things pyright alterted me to when I was reading something unrelated.
* We were using the wrong type for the `separators` field of `json.dumps`. This is defined as being a tuple, and only works by accident since Python strings are iterable.
* Pyright missed that `urllib.error` got imported transiently via something else. Might as well make it explicit.
=> A few minor tweaks

uv.lock
The locked version hasn't been upgraded for awhile.
=> deps: bump locked yt-dlp
