brozzler/behaviors.d/multiclicks.js.template
brozzler/behaviors.yaml

Hoping this will capture the first page from racineco.com document viewers.

multiclicks behavior for ARI-4838

---

brozzler/behaviors.d/facebook.js.template

log when we're trying to log into facebook and when we're not

better logs for facebook logins

---

brozzler/browser.py
brozzler/job.py
brozzler/job_schema.yml
brozzler/robots.py
brozzler/site.py
brozzler/worker.py
job-conf.rst

Currently excludes youtube-dl, this applies to requests made by Chrome and the robots.txt fetch.

Add user_agent option

---

brozzler/behaviors.d/instagram.js

update Instagram behavior, mostly css selectors

---

.github/PULL_REQUEST_TEMPLATE.md

Improve communication between review-seeker and reviewers (including folks in the future looking back at a specific change).
Adds a markdown file in a `.github/` folder at the root of this repo. See:
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
N/A
r: @nlevitt

add a github PR template for this repo

---

brozzler/browser.py

https://webarchive.jira.com/browse/ARI-5385
logging in at some sites redirects us to another URL; with this code, we subsequently return to the original URL—and run its behaviors
recrawl ARI-5385 facebook seeds

login and reload original url if navigated away

---

brozzler/behaviors.yaml
brozzler/js-templates/huffpostslides.js

[ARI-4868](https://webarchive.jira.com/browse/ARI-4868)
behavior for Huffington Post slideshow
crawl with brozzler seed http://www.huffingtonpost.com/2014/11/23/uva-sexual-assault_n_6209302.html

ARI-4868 behavior for Huffington Post slideshow

---

brozzler/behaviors.yaml

https://webarchive.jira.com/browse/ARI-5384
a simpleclicks behavior for recent issuu.com URLs
re-crawl https://issuu.com/msu_com/docs/communiquew14

simpleclicks for recent issuu.com URLs

---

brozzler/behaviors.yaml
brozzler/js-templates/pitchfork.js

ARI-5389
captures content at http://pitchfork.com/festival/chicago/
tested with qa crawl, no special deployment necessary

custom behavior for pitchfork.com, based on facebook & pm-gc-ca behaviors

---

brozzler/behaviors.yaml
brozzler/js-templates/pm-ca.js

ARI-5379
enables capture of item detail on pm.gc.ca news (and possibly other) pages—
simpleclicks fails here in an infinite loop as new elements are repeatedly created within each page
start a new standard crawl of each desired seed URL, or a brozzler crawl of pm.gc.ca, and review results

ARI-5379: custom behavior for pm.gc.ca

---

brozzler/behaviors.yaml

[ARI-5409 ](https://webarchive.jira.com/browse/ARI-5409)
captures content hidden behind accordion-style selectors at tuebingen.de

simpleclicks for tuebingen.de

---

brozzler/js-templates/facebook.js

ARI-5465
fix facebook behavior again

skip a.uiMorePagerPrimary after all

---

brozzler/behaviors.yaml
brozzler/js-templates/pm-ca.js

ARI-5379 too
apply behavior to _all_ site URLs

ARI 5379 URL regex update

---

brozzler/behaviors.yaml

ARI-5453
simpleclicks for some (maybe not all) wixsite.com nav menu links

simpleclicks for wixsite.com

---

brozzler/js-templates/instagram.js

ARI-5460
Update selectors and click to dismiss new sign-in pop-up

update Instagram selectors

---

README.rst

screenshots don't work with Xvfb

---

brozzler/behaviors.yaml

ARI-5259
click to capture additional pages
see ARI-5259

ARI-5259 blog.sina.com.cn pagination

---

brozzler/browser.py
brozzler/cli.py
brozzler/worker.py

sometimes we want to skip youtube_dl...
Tested so far with command line utility `brozzle-page`

skip_youtube_dl

---

brozzler/behaviors.yaml

simpleclicks for ARI-5241

---

brozzler/browser.py

This change provides a nice performance boost.

Use TCP_NODELAY in websocket connection to improve performance

---

brozzler/behaviors.yaml

capture citymedfordwi.civicweb.net minutes PDFs

---

brozzler/behaviors.yaml

umbraBehavior for thejewishnews.com

---

.travis.yml

travis-ci needs chromium 64 to pass tests

try to get chromium 64?

---

brozzler/browser.py

Useful to be able to tweak this value in other apps using `Browser`.

Make Browser._wait_for sleep time a varible

---

brozzler/__init__.py
brozzler/behaviors.yaml
brozzler/js-templates/umbraBehavior.js.j2

https://webarchive.jira.com/browse/ARI-5617
browse through https://americaspresidents.si.edu/gallery
adds skipIDcheck, onceOnly, configurable interval timing to umbraBehavior.js

repeatSameElement, firstMatchOnly, configurable interval timing, for ARI-5617

---

job-conf.rst
readme.rst

Little readability changes and one wayfinding addition for brozzler-dashboard access

Copy edits

---

README.rst
job-conf.rst
readme.rst

Resolves conflicts in #111 and restores 80 column width.

Karl readme copy edits

---

.travis.yml
README.rst
setup.py
tests/test_cli.py

Trying to figure out why the cli `--version` tests failed here
https://travis-ci.org/internetarchive/brozzler/builds/418919356

why did those tests fail???

---

brozzler/browser.py
brozzler/worker.py
tests/test_units.py

fetch service worker script with proper headers

---

brozzler/__init__.py
brozzler/chrome.py
brozzler/cli.py
brozzler/easy.py
brozzler/frontier.py
brozzler/robots.py
brozzler/worker.py
brozzler/ydl.py

We replace it everywhere in the code base.

logging.warn is deprecated and replaced by logging.warning

---

brozzler/ydl.py

... and update logging and fix a typo

capture soundcloud user page before capturing tracks

---

.travis.yml
README.rst
brozzler/frontier.py
pytest.ini
setup.py
tests/test_cluster.py
tests/test_frontier.py

For example
https://travis-ci.org/internetarchive/brozzler/jobs/592797411
wtf?

WIP: working on failing tests

---

brozzler/browser.py

The aim is to improve outlink quality.

Use urlcanon.whatwg in extracted outlinks

---

brozzler/js-templates/umbraBehavior.js.j2

Prioritize scrolling down in umbraBehavior, as does the custom facebook behavior.
I've checked the instagram behavior and @CorentinB's #168 with this update using brozzle_page.
I've also started new test crawls of a facebook seed.

scroll down, and down, then scroll up

---

brozzler/behaviors.yaml

adds selector for new Show More Posts button

instagram selector update

---

brozzler/chrome.py

identical code tested in qa branch

configurable websocket url timeout, default 60

---

brozzler/model.py

this update will require matching warcprox code & deployment.
it may also be good to try `brotlipy`

zlib compression for warcprox_meta blocks

---

brozzler/ydl.py

another update for yt-dlp v.2023.07.06, plus some code tidying

handle m3u8s

---

brozzler/cli.py
brozzler/dashboard/__init__.py
brozzler/frontier.py
brozzler/pywb.py
brozzler/worker.py
setup.py

This should probably replace PR #261.

update doublethink & rethinkdb imports

---

brozzler/ydl.py

format-sort fix

---

brozzler/behaviors.yaml

Capture more content from current https://www.moma.org/ artist pages

MOMA behavior

---

.github/workflows/python-formatting.yml
.gitignore
Makefile
brozzler/__init__.py
brozzler/browser.py
brozzler/chrome.py
brozzler/cli.py
brozzler/dashboard/__init__.py
brozzler/easy.py
brozzler/frontier.py
brozzler/model.py
brozzler/pywb.py
brozzler/robots.py
brozzler/worker.py
brozzler/ydl.py
setup.py
tests/test_brozzling.py
tests/test_cli.py
tests/test_cluster.py
tests/test_frontier.py
tests/test_units.py
vagrant/vagrant-brozzler-new-job.py
vagrant/vagrant-brozzler-new-site.py

The Makefile is configured to run black to format with support for py35 - py312.

Use black, enforce with GitHub Actions

---

brozzler/behaviors.yaml
setup.py

also tightens setup.py rethinkdb dependency

add eldo.lu cookies dialog selector to defaults

---

brozzler/chrome.py

Ref: https://developer.chrome.com/docs/chromium/new-headless

Use --headless=new or --headless=chrome if supported

---

pyproject.toml
setup.py

for https://pypi.org/project/brozzler/1.6.2/

minor updates for v.1.6.2 (for pypi)

---

brozzler/cli.py

On macOS, we can find Chrome even if it's installed in a non-default path by querying `mdfind`. This is the CLI entrypoint to Spotlight, and we can use it to look up applications using their unique bundle identifiers.
If `mdfind` fails to find anything, this falls back to the hardcoded paths. This should ensure this still works if Spotlight indexing is off, but Chrome is in the default path. If we'd prefer, I can switch this to looking up the hardcoded paths first and fall back to `mdfind` if that doesn't work instead.

CLI: improve Chrome finding on Mac

---

brozzler/chrome.py

Fix for https://webarchive.jira.com/browse/WWM-2292 (as seen by pyspn)

Try new flag to disable auto http->https

---

.github/workflows/release.yml

Applies fixes from https://github.com/internetarchive/warcprox/pull/220.

ci: fix publish needs write permissions

---

uv.lock

warcprox 2.7.0

---

.github/workflows/dependabot.yml
dependabot.yml
scripts/ytdlp_test.py

Also sets up an auto-approve for dependabot PRs.

dependabot: add yt-dlp in qa

---

pyproject.toml
setup.py

Dependabot seems to be having trouble parsing our extras; see if this fixes it.
Should we just move the remaining `setup.py` items over at this point?

deps: move to pyproject.toml

---

.gitignore

These are created by some tests.

gitignore: ignore warcprox files

---

brozzler/cli.py

This makes it easier to test the new video exclusion work.

brozzler-new-site: add flag to disable videos

---

.github/workflows/daily.yaml
tests/test_frontier.py

I migrated our regular tests to use `uv`, but neglected to update this config too.

ci: fix daily run
